### ISSUE TITLE
Problem with the compiled release binaries

### ISSUE THREAD

**Issue by w00lf** [lutaml/expressir#63] opened 2021-02-09 11:11 UTC
When tried to use the latest version of lutaml with expressir 0.2.10 got this error - https://github.com/lutaml/lutaml/pull/14/checks?check_run_id=1861464629
```
LoadError:
  cannot load such file -- D:/a/lutaml/lutaml/vendor/bundle/ruby/2.5.0/gems/expressir-0.2.10-x64-mingw32/lib/expressir/express_exp/express_parser
```
It seems like some kind of error with the compiled binary

**Comment by CAMOBAP** [comment] 2021-02-09 12:29
Here is a list of reported dependencies:

```
x86_64-w64-mingw32-objdump -p expressir-0.2.10-x64-mingw32/data/lib/expressir/express_exp/2.5/express_parser.so | grep 'DLL Name:'
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
	DLL Name: libwinpthread-1.dll
	DLL Name: libstdc++-6.dll
	DLL Name: x64-msvcrt-ruby250.dll
```

`libwinpthread-1.dll` and `libstdc++-6.dll` under suspect...

**Comment by CAMOBAP** [comment] 2021-02-11 08:46
Both of those libraries are available. Locally I cannot reproduce "127: The specified procedure could not be found." only "ruby 126: The specified module could not be found."

Investigation in progress

**Comment by CAMOBAP** [comment] 2021-02-17 20:06
@zakjan to be on the same page do we have any tests which call native parser code?

**Comment by zakjan** [comment] 2021-02-18 07:58
Yes, all tests in https://github.com/lutaml/expressir/tree/master/spec that call Parser.from_exp

**Comment by CAMOBAP** [comment] 2021-02-20 08:32
- `express_parser-orig.so` - the one from platform gem (from rubygems.org) - doesn't work 126/127 issues
 - `express_parser.so` - the one from GHA CI - works

<img width="1212" alt="Screen Shot 2021-02-20 at 11 23 31 AM" src="https://user-images.githubusercontent.com/2169738/108589372-0822e200-736f-11eb-8acc-666f3cb56f27.png">

The one difference is that `express_parser-orig.so` require `user32.dll` but this cannot be the case, I think that load order makes sens here, investigation still in progress

**Comment by CAMOBAP** [comment] 2021-03-07 12:28
Also, I have tried to analyze OS even journal with Process Monitor but no success yet...

**Comment by CAMOBAP** [comment] 2021-03-10 09:48
@zakjan FYI it's now possible to do release just from GH web sitehttps://github.com/lutaml/expressir/commit/7f2737f9fe4ca8d2278d90e93dcf056d15a9e4b1

You can select the next version and triggered release workflow manually.

In my opinion, it's not a primary way to do releases, but can be useful in some cases for instance: all changes already in the repo and you just need to trigger the release, and you are AFK

Let me know if you have any feedback about this

**Comment by CAMOBAP** [comment] 2021-03-10 15:35
@w00lf fixed version of `expressir` was pushed to rubygems.org

Tests in `lutaml` still failing because https://github.com/lutaml/lutaml-express/commit/c304d32f8a4913c6ac67bc1c1cbf938b19acac00 need to be released

I'm closing this one

**Closed by CAMOBAP** 2021-03-10 15:35 UTC
Labels: bug
