### ISSUE TITLE
bundle install is crashing on Ubuntu with Ruby 2.7

### ISSUE THREAD

**Issue by HassanAkbar** [lutaml/expressir#141] opened 2023-12-21 08:30 UTC
GitHub Actions are failing for `ubuntu` with ruby `2.7` because `expressir 1.3.0` is unavailable for `x86_64-linux`.

Example workflow runs
- https://github.com/glossarist/concept-model/actions/runs/7285443827/job/19852360169?pr=37
- https://github.com/metanorma/stepmod-utils/actions/runs/7262578577/job/19786021064

**Comment by maxirmx** [comment] 2023-12-21 09:59
@HassanAkbar 
I am afraid it will require some research. I have it installing ```expressir-1.3.0-x86_64-linux-gnu``` as expected so it may be an issue with different bundler version

```
maxirmx@MSS-WS-N:~/Projects/expressir$ rbenv rehash
maxirmx@MSS-WS-N:~/Projects/expressir$ rbenv global 2.7.8
maxirmx@MSS-WS-N:~/Projects/expressir$ ruby --version
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]
maxirmx@MSS-WS-N:~/Projects/expressir$ gem install expressir
Fetching thor-1.3.0.gem
Fetching expressir-1.3.0-x86_64-linux-gnu.gem
Successfully installed thor-1.3.0
Successfully installed expressir-1.3.0-x86_64-linux
Parsing documentation for thor-1.3.0
Installing ri documentation for thor-1.3.0
Parsing documentation for expressir-1.3.0-x86_64-linux
Installing ri documentation for expressir-1.3.0-x86_64-linux
Done installing documentation for thor, expressir after 1 seconds
2 gems installed
maxirmx@MSS-WS-N:~/Projects/expressir$ bundler --version
Bundler version 2.1.4
maxirmx@MSS-WS-N:~/Projects/expressir$ 
```

**Comment by maxirmx** [comment] 2023-12-21 10:10
The note above was Ubuntu 20
Clean Ubuntu 22 works as well. I am lost completely
```
maxirmx@MSS-WS-N:~/Projects/expressir$ bundler --version
Bundler version 2.4.10
maxirmx@MSS-WS-N:~/Projects/expressir$ gem info expressir

*** LOCAL GEMS ***


maxirmx@MSS-WS-N:~/Projects/expressir$ gem install expressir
Fetching expressir-1.3.0-x86_64-linux-gnu.gem
Successfully installed expressir-1.3.0-x86_64-linux-gnu
Parsing documentation for expressir-1.3.0-x86_64-linux-gnu
Installing ri documentation for expressir-1.3.0-x86_64-linux-gnu
Done installing documentation for expressir after 0 seconds
1 gem installed

A new release of RubyGems is available: 3.4.10 → 3.5.1!
Run `gem update --system 3.5.1` to update your installation.
```

**Comment by ronaldtse** [comment] 2023-12-21 10:31
@maxirmx the issue seems to be the difference between the old `x86_64-linux` and the new `x86_64-linux-gnu`?

**Comment by maxirmx** [comment] 2023-12-21 10:37
The issue is that bundler shall fetch  ```expressir-1.3.0-x86_64-linux-gnu.gem```  but on GHA it attempts to fetch ```expressir-1.3.0-x86_64-linux.gem``` that does not exist

**Comment by HassanAkbar** [comment] 2023-12-21 10:44
@maxirmx One thing that I noticed is that older versions were available for `x86_64-linux` distributions but version `1.3.0` is only available for `x86_64-linux-gnu`. 

<img width="722" alt="Screenshot 2023-12-21 at 3 27 49 PM" src="https://github.com/lutaml/expressir/assets/5301572/3848dba8-5e46-40d2-8035-efa33002ba2d">

<img width="722" alt="Screenshot 2023-12-21 at 3 27 39 PM" src="https://github.com/lutaml/expressir/assets/5301572/613b5a22-aba0-4aa3-b355-0bc7362f25a5">


and the error in the workflow states that 

> Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/expressir-1.3.0-x86_64-linux.gem)

So I think this is what's causing the workflow to fail.

**Comment by HassanAkbar** [comment] 2023-12-21 10:46
> The issue is that bundler shall fetch `expressir-1.3.0-x86_64-linux-gnu.gem` but on GHA it attempts to fetch `expressir-1.3.0-x86_64-linux.gem` that does not exist

@maxirmx Yes, just saw your comment after posting mine.

**Comment by maxirmx** [comment] 2023-12-21 11:55
[x86_64-linux has been changed to x86_64-linux-gnu intentionally](https://github.com/lutaml/expressir/pull/138#issue-2038471696)
Legacy x86_64-linux versions actually support gnu flavor only and it caused [issues]( https://github.com/lutaml/expressir/issues/106)

Pls have a look at these two runs:
-  https://github.com/maxirmx/concept-model/actions/runs/7287677888/job/19858789100
-  https://github.com/maxirmx/concept-model/actions/runs/7287295439/job/19857673079

setup-ruby GHA action upgrades bundler by default but does not do required rubygems upgrade
If I upgrade rubygems to the version that corresponds to bundler version everything works
If I downgrade bundler to the version to corresponds to default rubygems version  it also works

Not sure what would be the best approach to fix it.
Options are:
- use bundler 2.1.xx       -- fix it in metanorma ci scripts and possibly indvidually for some gems
- upgrade rubygems to 3.4.22 -- fix it in metanorma ci scripts and possibly indvidually for some gems
- rollback gnu/musl separation in expressir for Ruby 2.7

@ronaldtse, what do you think ? 
I think we shall ask @CAMOBAP  as well

**Comment by opoudjis** [comment] 2023-12-22 00:58
Just pointing out folks that Ruby 3.3 is coming out in a few days, and that means that we would be withdrawing Ruby 2.7 soon anyway. @ronaldtse is it worth persisting with fixing this at all, or is this our hint to drop Ruby 2.7 support?

**Comment by ronaldtse** [comment] 2023-12-22 01:11
Clearly the cause is due to incompatibility between Bundler and Rubygems versions, so the only option is:

> * upgrade rubygems to 3.4.22 -- fix it in metanorma ci scripts and possibly indvidually for some gems

@CAMOBAP could you please help with this?

@opoudjis yes we should withdraw 2.7 support soon but we shouldn't leave it in a state of arrears when we do formally drop Ruby 2.x complete (2.7 is the last 2.x).

**Comment by CAMOBAP** [comment] 2023-12-22 05:20
@ronaldtse should be fixed in the scope https://github.com/metanorma/ci/issues/136 already

**Comment by maxirmx** [comment] 2023-12-22 09:02
@HassanAkbar 
https://github.com/metanorma/stepmod-utils now works on Ruby 2.7 (after https://github.com/metanorma/ci/issues/136 fix)

https://github.com/glossarist/concept-model  needs make.yml fix.  There is a note in the file saying that it is auto-generated so I am not suggesting a fix

**Comment by ronaldtse** [comment] 2023-12-22 10:55
I’ve tried the fix by fully rerunning tests on Metanorma-standoc , and verified it works. Thank you @CAMOBAP ! Feel free to close this when ready.

**Closed** 2023-12-22 16:31 UTC
